language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

script: mvn clean deploy source:jar javadoc:javadoc --settings travis_settings.xml

# travis encrypt -r nhl/bootique-mvc "CI_DEPLOY_USERNAME='name'"
# travis encrypt -r nhl/bootique-mvc "CI_DEPLOY_PASSWORD='password'"
env:
  global:
    - secure: "o8ypXC5fI5GydJ/pVD7uajxxH90nnXXFL/PFBF8mUvB7kJ38jw5bIYIBN8KoiOJL/ZvmCNquIsB//BuD/E7K4/BoCwv/pq8IFJSYHS+3mhCrGE96yWa8eZy+miqvqQZD4ZSuIjfbrxLSTIlSpoz1dDnlAjeRYaNV/azMH0VW5bG72a5co2yTDc2mJFeuatI0W/5yZo5OTIRgzcexWsFT9xOB0EI2pzOA7zQtnNSXtJeey9Uh775boAq47youw3HvI/ckHtf2a0bpekD99dYG9lRJBOtChSfdOaEh44f/CDk2AkEOqpLoy9NRQ+XW8P3PpNxLEizSRt1uY+ksUIFVavWsOIwETO54iQp0p4aWOmrC402eRw2ANjYUlck/903/0HWm5Bh/MsP4h93hgjb9pcl56/ILCk3pj5CxkB5mlpdf09hiF4mG4G5osV+wAiIj9Cs4rjTd0YBjUcCcjdkmOeA4bqFBIA44Mrgu6FW0p3whQ4tBBNGCWD9v6p7SwLpb/jM0jenliugeaf0bJaopi2aZyhk9cu1PJoim2MaL51L0ahBXNooNMX1m1lvSE9sIJumqlac8BWVcgRdoqP3cUaZsrfco2G3c0rLsxuxf2mAJTutP5dvSGJPQ8toyVfOhDdsAqjgBZGSypaqQLXaEkTKeGaxkEBqgzWTGvsJyW6I="
    - secure: "j2w5TohI/gqH258ULlH6xbMOfOIskM7fEO5uYXZjXQ6rR/jI7TCjHmlKPKzFFbiwW3XYZ8excke79bQr9nsJeE8CAHp9pykorE7jGY974H80NdOFtyHVqS5isHXGtnmjRj6SOIwas907KkDxA0ASU9cSx5rx2vqdmA0/3+yKim8f0/5D+M93BAWELbLbEaLCidl7HN+tbG/itZm1FGQ5AGbJSQ+4O7ttkyUNOKUQ0GvGbk+OQkkFBb6DB3BB0HQNNuJ0dB96NawbzjVDJNZTBsWMpCuca6lYfJuf0aX3a2Lb5t80X8VZTv3puLxlhqWw05GtPpUIHs2PJS1MkyAbmOJlu/nooDC1MteGlkx/sGOjlvYZSXJi0rspOjpjh88IxlRl1zx1l4H6z5OLIIA1GdZGyhyW3OyduDOMXvWD2QKfGIVa31TiW+s2HKyL01aj15QZQ4gVl2ZgQ7vv5BpGkWvkJjcQ61RmqGC3zWGHI0+HW1SUlFGV2U0z2OeoBTTvYE1deioB0jGl5i20g+Uas2tK8RpzMONdCLnS/jcytDxvbW6y3CVrFojFh57w9EpOIMW2SyI+fm9Sg061zhNXJ+oaTmc8Sj+fu5e7XpnAzJN0EXSyN7q5w0iH1Njds3UYZyiMdlilzCyrtVR9t6rz/S3kvxAdn9g814nlM/1rQtc="
